In [ ]:
import pandas as pd

In [43]:
import pymysql
from sqlalchemy import create_engine

In [33]:
df=pd.read_csv('Walmart.csv')

In [3]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [5]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [6]:
df.shape

(10051, 11)

In [7]:
df.duplicated().sum()

np.int64(51)

In [34]:
df.drop_duplicates(inplace=True)

In [18]:
df.shape

(10000, 11)

In [20]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [35]:
df.dropna().sum()

invoice_id                                                 49945852
Branch            WALM003WALM048WALM067WALM064WALM013WALM026WALM...
City              San AntonioHarlingenHaltom CityBedfordIrvingDe...
category          Health and beautyElectronic accessoriesHome an...
unit_price        $74.69$15.28$46.33$58.22$86.31$85.39$68.84$73....
quantity                                                    23483.0
date              05/01/1908/03/1903/03/1927/01/1908/02/1925/03/...
time              13:08:0010:29:0013:23:0020:33:0010:37:0018:30:...
payment_method    EwalletCashCredit cardEwalletEwalletEwalletEwa...
rating                                                      58107.7
profit_margin                                               3925.23
dtype: object

In [25]:
df.dropna(inplace=True)

In [26]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [28]:
df.head(-1)

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48
...,...,...,...,...,...,...,...,...,...,...,...
9994,9995,WALM030,Richardson,Home and lifestyle,$62,1.0,15/02/21,9:04:00,Cash,3.0,0.48
9995,9996,WALM056,Rowlett,Fashion accessories,$37,3.0,03/08/23,10:10:00,Cash,3.0,0.33
9996,9997,WALM030,Richardson,Home and lifestyle,$58,2.0,22/02/21,14:20:00,Cash,7.0,0.48
9997,9998,WALM050,Victoria,Fashion accessories,$52,3.0,15/06/23,16:00:00,Credit card,4.0,0.48
9998,9999,WALM032,Tyler,Home and lifestyle,$79,2.0,25/02/21,12:25:00,Cash,7.0,0.48

In [36]:
df['unit_price']=df['unit_price'].str.replace('$','').astype(float)

In [37]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10000 non-null  int64
 1   Branch          10000 non-null  str
 2   City            10000 non-null  str
 3   category        10000 non-null  str
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            10000 non-null  str
 7   time            10000 non-null  str
 8   payment_method  10000 non-null  str
 9   rating          10000 non-null  float64
 10  profit_margin   10000 non-null  float64
dtypes: float64(4), int64(1), str(6)
memory usage: 859.5 KB

In [39]:
df['unit_price'].info()

<class 'pandas.Series'>
RangeIndex: 10000 entries, 0 to 9999
Series name: unit_price
Non-Null Count  Dtype
--------------  -----
9969 non-null   float64
dtypes: float64(1)
memory usage: 78.3 KB

In [40]:
df.describe()

        invoice_id   unit_price     quantity        rating  profit_margin
count  10000.00000  9969.000000  9969.000000  10000.000000   10000.000000
mean    5000.50000    50.622142     2.355602      5.830170       0.393813
std     2886.89568    21.203766     1.605455      1.764097       0.090656
min        1.00000    10.080000     1.000000      3.000000       0.180000
25%     2500.75000    32.000000     1.000000      4.000000       0.330000
50%     5000.50000    51.000000     2.000000      6.000000       0.330000
75%     7500.25000    69.000000     3.000000      7.000000       0.480000
max    10000.00000    99.960000    10.000000     10.000000       0.570000

In [42]:
df.to_csv('walmart_cleaned_data2.csv',index=False)

In [ ]:
## make a connection with mysql
# mysql 
# host = localhost
# port = 3306
# user = root
# password = 'your_password'

## make a connection with postgresql
# psql
# host = localhost
# port = 5432
# user = postgres
# password = 'x0000'

In [44]:
from urllib.parse import quote_plus
password=quote_plus("rjabhinav@2002")
engine_mysql=create_engine(f"mysql+pymysql://root:{password}@localhost:3306/walmart_db")
try:
    engine_mysql
    print("Connected to mysql database")
except:
    print("not connected!!")

Connected to mysql database

In [46]:
df.to_sql(name='walmart',con=engine_mysql,if_exists='replace',index=False)

10000